### ISSUE TITLE
"Error: undefined" when attempting to add kasm as a new catalog on TrueNAS-SCALE-23.10.0.1

### ISSUE THREAD

**Issue by donovan-middleton** [kasmtech/kasm-truenas-charts#2]
When attempting to follow the instructions to add a new catalog on TrueNAS-SCALE-23.10.0.1 as described in the [README.md](https://github.com/kasmtech/kasm-truenas-charts/blob/develop/README.md), I get the following error message:
```
Error: undefined
'catalog.json' metadata file must be specified for a valid catalog
remove_circle_outline
More info...
 Error: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 426, in run
    await self.future
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 464, in __run_body
    rv = await self.method(*([self] + args))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/service/crud_service.py", line 194, in nf
    rv = await func(*args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 44, in nf
    res = await f(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 177, in nf
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/catalogs_linux/update.py", line 262, in do_create
    verrors.check()
  File "/usr/lib/python3/dist-packages/middlewared/service_exception.py", line 70, in check
    raise self
middlewared.service_exception.ValidationErrors: [EINVAL] cached_catalog_file: 'catalog.json' metadata file must be specified for a valid catalog
```
As I'm new to adding kasm, I'm guessing I missed something?

**Comment by unicaller** [comment]
'catalog.json' metadata file must be specified for a valid catalog

**Comment by donovan-middleton** [comment]
So...  To me, it appears there is a catalog.json file missing from the root of this repository.

I'm entering this:
![image](https://github.com/kasmtech/kasm-truenas-charts/assets/45984475/ea5c6787-106f-4111-bd22-d1e00ef8d8ee)

And I get this:
![image](https://github.com/kasmtech/kasm-truenas-charts/assets/45984475/00992047-338c-413c-ba62-3cdbafa4ba35)

BTW: I have now upgraded to TrueNAS-SCALE-23.10.1. The issue has not changed for me though.

I have successfully loaded the TrueCharts catalog found here: https://github.com/truecharts/catalog
And that one does have a catalog.json file in the root of their repository, so I don't believe it is my TrueNAS Scale instance!

As a minor note... On the [README.md](https://github.com/kasmtech/kasm-truenas-charts/blob/develop/README.md) page, there is also a misspelling.
"To add this Catalog to TrueNAS SCALE click on Apps -> Manage Catalogs -> Add Catalog and set the following **_vbariables_**:"

**Comment by cloudmainc** [comment]
I'm getting the same thing too.
